// bullets/src/main.tsx
import { render } from "solid-js/web";
import type { DocHandle } from "@automerge/automerge-repo";
import { datatype } from "./datatype.ts";
import type { BulletsDoc } from "./datatype.ts";

export const plugins = [
  {
    type: "patchwork:datatype" as const,
    id: "bullets",
    name: "Bullets",
    icon: "List",
    async load() {
      return datatype;
    },
  },
  {
    type: "patchwork:tool" as const,
    id: "bullets",
    name: "Bullets",
    supportedDataTypes: ["bullets"],
    async load() {
      const { BulletsTool } = await import("./tool.tsx");
      return (handle: DocHandle<BulletsDoc>, element: HTMLElement) => {
        return render(
          () => <BulletsTool handle={handle} element={element} />,
          element
        );
      };
    },
  },
];

// sequencer/src/main.tsx
import ReactDOM from "react-dom/client";
import "./style.css";
import { Repo } from "@automerge/automerge-repo";
import { RepoContext } from "@automerge/react/slim";
import { dataType } from "./datatype";

export const plugins = [
  {
    type: "patchwork:datatype",
    id: "sequencer",
    name: "Sequencer",
    icon: "Music",
    async load() {
      return dataType;
    },
  },
  {
    type: "patchwork:tool",
    id: "sequencer",
    name: "Sequencer",
    supportedDatatypes: ["sequencer"],
    async load() {
      const { Sequencer } = await import("./tool");
      return (handle: any, element: HTMLElement & { repo: Repo }) => {
        console.log("[Sequencer] Startup with handle.url:", handle.url);
        const root = ReactDOM.createRoot(element);

        root.render(
          <RepoContext.Provider value={element.repo}>
            <Sequencer docUrl={handle.url} element={element} />
          </RepoContext.Provider>
        );
        return () => root.unmount();
      };
    },
  },
];
