// nsync-indicator/src/index.tsx
import type { ToolImplementation } from "@inkandswitch/patchwork-plugins";

export const plugins = [
  {
    type: "patchwork:tool",
    id: "sync-indicator",
    tags: ["titlebar-tool"],
    name: "Sync Indicator",
    icon: "Wifi",
    supportedDatatypes: "*" as const,
    unlisted: true,
    forTitleBar: true,
    async load(): Promise<ToolImplementation> {
      const { render } = await import("solid-js/web");
      const { SyncIndicator, RepoContext } = await import("./SyncIndicator");
      return (handle, element) => {
        element.style.width = "fit-content";
        element.style.zIndex = "10";

        const dispose = render(
          () => (
            <RepoContext.Provider value={element.repo}>
              <SyncIndicator handle={handle} />
            </RepoContext.Provider>
          ),
          element
        );
        return () => dispose();
      };
    },
  },
];

// quiet-mode/src/index.tsx
import { Plugin, ToolImplementation } from "@inkandswitch/patchwork-plugins";
import { render } from "solid-js/web";
import type { AccountDoc } from "./types";

export const plugins: Plugin<any>[] = [
  {
    type: "patchwork:tool",
    id: "quiet-frame",
    tags: ["frame-tool"],
    name: "Quiet Frame",
    icon: "Window",
    supportedDatatypes: ["account"],
    async load(): Promise<ToolImplementation<AccountDoc>> {
      const { PatchworkFrame } = await import("./frame/PatchworkFrame");
      return (handle, element) => {
        return render(
          () => (
            <PatchworkFrame
              handle={handle}
              element={element}
              repo={element.repo}
            />
          ),
          element
        );
      };
    },
  },
];
