// nsync-indicator/src/index.tsx
import type { ToolImplementation } from "@inkandswitch/patchwork-plugins";

export const plugins = [
  {
    type: "patchwork:tool",
    id: "sync-indicator",
    tags: ["titlebar-tool"],
    name: "Sync Indicator",
    icon: "Wifi",
    supportedDatatypes: "*" as const,
    unlisted: true,
    forTitleBar: true,
    async load(): Promise<ToolImplementation> {
      const { render } = await import("solid-js/web");
      const { SyncIndicator, RepoContext } = await import("./SyncIndicator");
      return (handle, element) => {
        element.style.width = "fit-content";
        element.style.zIndex = "10";

        const dispose = render(
          () => (
            <RepoContext.Provider value={element.repo}>
              <SyncIndicator handle={handle} />
            </RepoContext.Provider>
          ),
          element
        );
        return () => dispose();
      };
    },
  },
];

// mimi-history/src/index.tsx
import { render } from "solid-js/web";
import {
  Plugin,
  type ToolImplementation,
} from "@inkandswitch/patchwork-plugins";
import { HistoryGroupingsDoc } from "./types";

export const plugins: Plugin<any>[] = [
  {
    type: "patchwork:datatype",
    id: "patchwork:history-change-groups",
    name: "Document History Change Groups",
    icon: "History",
    unlisted: true,
    async load() {
      return {
        init: (doc: HistoryGroupingsDoc) => {
          if (!doc.sourceDocumentUrl) return;
          Object.assign(doc, {
            ["@patchwork"]: { type: "patchwork:history-change-groups" },
            version: doc.version || 1,
            sourceDocumentUrl: doc.sourceDocumentUrl,
            updatedAt: doc.updatedAt || 0,
            throttleMs: doc.throttleMs || 30 * 60 * 1000,
            heads: doc.heads || [],
            groupings: doc.groupings || {},
          } as HistoryGroupingsDoc);
        },
        getTitle: (doc: HistoryGroupingsDoc) => {
          return `History Change Groups for ${doc.sourceDocumentUrl}`;
        },
      };
    },
  },
  {
    type: "patchwork:tool",
    id: "history-view",
    name: "History",
    icon: "History",
    supportedDatatypes: ["account"],
    async load(): Promise<ToolImplementation<any>> {
      const { HistoryTimeline } = await import("./history/HistoryTimeline");
      return function (_handle, element) {
        return render(() => <HistoryTimeline repo={element.repo} />, element);
      };
    },
  },
];
